[package]
name = "todo"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.23", features = ["derive"] }
dirs = "5.0.1"
toml = "0.8.19"
serde = { version = "1.0.215", features = ["derive"] }
crossterm = "0.28.1"
